[08-May-21 22:07:50] [Scholapp server] [Process: 6679] [Scholapp] - INFO - Setting up flask_microservices.test_microservice.test_app
[08-May-21 22:07:50] [Scholapp server] [Process: 6679] [Scholapp] - INFO - Deserializing tests
[08-May-21 22:07:50] [Scholapp server] [Process: 6679] [Scholapp] - INFO - Setting up was successful
[08-May-21 22:08:46] [Scholapp server] [Process: 6679] [Scholapp] - INFO - Test added: 9ed405aa-8318-3720-98e5-60ad8c08be04
[08-May-21 22:08:46] [Scholapp server] [Process: 6679] [Scholapp] - ERROR - Traceback (most recent call last):
  File "/home/idan/Desktop/final_proj/Final-Project-Server/utilities/decorators/in_try_catch.py", line 11, in wrapper
    return func(*args, **kwargs)
  File "/home/idan/Desktop/final_proj/Final-Project-Server/flask_microservices/test_microservice/test_app.py", line 383, in actual_add_test
    self._test_container.add_test(Test().from_json(flask.request.get_json()))
  File "/home/idan/Desktop/final_proj/Final-Project-Server/server/test_manager/data_containers/test.py", line 190, in from_json
    self.serialize()
  File "/home/idan/Desktop/final_proj/Final-Project-Server/server/test_manager/data_containers/test.py", line 136, in serialize
    pickled_file = Path(self._set_pickled_file_path())
  File "/usr/lib/python3.8/pathlib.py", line 1038, in __new__
    self = cls._from_parts(args, init=False)
  File "/usr/lib/python3.8/pathlib.py", line 679, in _from_parts
    drv, root, parts = self._parse_args(args)
  File "/usr/lib/python3.8/pathlib.py", line 663, in _parse_args
    a = os.fspath(a)
TypeError: expected str, bytes or os.PathLike object, not NoneType

