[08-May-21 19:53:13] [Scholapp server] [Process: 5338] [Scholapp] - INFO - Setting up flask_microservices.test_microservice.test_app
[08-May-21 19:53:13] [Scholapp server] [Process: 5338] [Scholapp] - INFO - Setting up was successful
[08-May-21 20:52:47] [Scholapp server] [Process: 5338] [Scholapp] - ERROR - Traceback (most recent call last):
  File "/home/idan/Desktop/final_proj/Final-Project-Server/utilities/decorators/in_try_catch.py", line 11, in wrapper
    return func(*args, **kwargs)
  File "/home/idan/Desktop/final_proj/Final-Project-Server/flask_microservices/test_microservice/test_app.py", line 382, in actual_add_test
    self._test_container.add_test(Test().from_json(flask.request.get_json()))
  File "/home/idan/Desktop/final_proj/Final-Project-Server/server/test_manager/data_containers/test.py", line 167, in from_json
    if len(json_val["questions"]) == 0:
KeyError: 'questions'

[08-May-21 20:56:34] [Scholapp server] [Process: 5338] [Scholapp] - ERROR - Traceback (most recent call last):
  File "/home/idan/Desktop/final_proj/Final-Project-Server/utilities/decorators/in_try_catch.py", line 11, in wrapper
    return func(*args, **kwargs)
  File "/home/idan/Desktop/final_proj/Final-Project-Server/flask_microservices/test_microservice/test_app.py", line 382, in actual_add_test
    self._test_container.add_test(Test().from_json(flask.request.get_json()))
  File "/home/idan/Desktop/final_proj/Final-Project-Server/server/test_manager/data_containers/test.py", line 168, in from_json
    raise Exception("The questions cannot be an empty list!!!")
Exception: The questions cannot be an empty list!!!

[08-May-21 20:59:14] [Scholapp server] [Process: 5338] [Scholapp] - ERROR - Traceback (most recent call last):
  File "/home/idan/Desktop/final_proj/Final-Project-Server/utilities/decorators/in_try_catch.py", line 11, in wrapper
    return func(*args, **kwargs)
  File "/home/idan/Desktop/final_proj/Final-Project-Server/flask_microservices/test_microservice/test_app.py", line 382, in actual_add_test
    self._test_container.add_test(Test().from_json(flask.request.get_json()))
  File "/home/idan/Desktop/final_proj/Final-Project-Server/server/test_manager/data_containers/test.py", line 168, in from_json
    raise Exception("The questions cannot be an empty list!!!")
Exception: The questions cannot be an empty list!!!

[08-May-21 20:59:54] [Scholapp server] [Process: 5338] [Scholapp] - ERROR - Traceback (most recent call last):
  File "/home/idan/Desktop/final_proj/Final-Project-Server/utilities/decorators/in_try_catch.py", line 11, in wrapper
    return func(*args, **kwargs)
  File "/home/idan/Desktop/final_proj/Final-Project-Server/flask_microservices/test_microservice/test_app.py", line 382, in actual_add_test
    self._test_container.add_test(Test().from_json(flask.request.get_json()))
  File "/home/idan/Desktop/final_proj/Final-Project-Server/server/test_manager/data_containers/test.py", line 176, in from_json
    self._date = json_val["date"]
KeyError: 'date'

